config/routes.rb
Delayed::Web::Engine.routes.draw do
  root to: 'jobs#index'

  scope '/:queue' do
    resources :jobs, only: [:destroy, :index, :show] do
      put :queue, on: :member
    end
  end
end

app/models/delayed/dashboard/job.rb
require 'forwardable'

module Delayed
  module Dashboard
    class Job
      extend SingleForwardable

      def_delegator :backend, :all
      def_delegator :backend, :find

      # Set the backend you're using for Delayed::Job.
      #
      # Example:
      #   Delayed::Dashboard::Job.backend = :active_record
      #
      # @param new_backend [String] "active_record" or "double".
      #
      # @return [void]
      def self.backend= new_backend
        @backend = "Delayed::Dashboard::Job::#{new_backend.classify}".constantize
      end

      def self.backend
        @backend
      end
    end
  end
end

app/models/delayed/dashboard/job/active_record.rb
module Delayed
  module Dashboard
    class Job::ActiveRecord
      def self.find *args
        Delayed::Job.find *args
      end

      def self.all
        Delayed::Job.limit 100
      end
    end
  end
end

app/models/delayed/dashboard/job/double.rb
module Delayed
  module Dashboard
    class Job::Double
      attr_accessor :id
      attr_accessor :created_at
      attr_accessor :run_at
      attr_accessor :attempts
      attr_accessor :locked_at
      attr_accessor :locked_by
      attr_accessor :last_error
      attr_accessor :handler

      def initialize attributes = {}
        @id         = attributes[:id]
        @created_at = attributes[:created_at]
        @run_at     = attributes[:run_at]
        @attempts   = attributes[:attempts]
        @locked_at  = attributes[:locked_at]
        @locked_by  = attributes[:locked_by]
        @last_error = attributes[:last_error]
        @handler    = attributes[:handler]
      end

      def to_param
        id
      end

      def self.find *args
        all.sample
      end

      def self.all
        [build_executing, build_failed, build_queued]
      end

      def self.build_executing
        new id: 1, created_at: 1.minute.ago, run_at: 1.minute.ago,
          attempts: 1, last_error: nil, locked_at: 30.seconds.ago,
          locked_by: 'host.local', handler: '---'
      end

      def self.build_failed
        new id: 2, created_at: 5.hours.ago, run_at: 2.hours.from_now,
          attempts: 4, last_error: 'RuntimeError: RuntimeError',
          locked_at: nil, locked_by: nil, handler: '---'
      end

      def self.build_queued
        new id: 3, created_at: 30.seconds.ago, run_at: 30.seconds.ago,
          attempts: 0, last_error: nil, locked_at: nil, locked_by: nil,
          handler: '---'
      end
    end
  end
end

app/models/delayed/web/job.rb
require 'forwardable'

module Delayed
  module Web
    class Job
      extend SingleForwardable

      def_delegator :backend, :by_queue
      def_delegator :backend, :find

      # Set the backend you're using for Delayed::Job.
      #
      # Example:
      #   Delayed::Web::Job.backend = :active_record
      #
      # @param new_backend [String] "active_record" or "double".
      #
      # @return [void]
      def self.backend= new_backend
        @backend = "Delayed::Web::Job::#{new_backend.classify}".constantize
      end

      def self.backend
        @backend
      end

      def self.queues
        @queues ||= []
      end
    end
  end
end

app/models/delayed/web/job/active_record.rb
module Delayed
  module Web
    class Job::ActiveRecord
      def self.find *args
        decorate Delayed::Job.find(*args)
      end

      def self.by_queue name
        jobs = Delayed::Job.order('id DESC').limit(100)
        jobs = jobs.where(queue: name) if name.present?
        jobs

        Enumerator.new do |enumerator|
          jobs.each do |job|
            enumerator.yield decorate(job)
          end
        end
      end

      def self.decorate job
        job = StatusDecorator.new job
        job = ActiveRecordDecorator.new job
        job
      end
    end
  end
end

app/models/delayed/web/job/double.rb
module Delayed
  module Web
    class Job::Double
      attr_accessor :id
      attr_accessor :created_at
      attr_accessor :run_at
      attr_accessor :queue
      attr_accessor :attempts
      attr_accessor :failed_at
      attr_accessor :locked_at
      attr_accessor :locked_by
      attr_accessor :last_error
      attr_accessor :handler

      def initialize attributes = {}
        @id         = attributes[:id]
        @created_at = attributes[:created_at]
        @run_at     = attributes[:run_at]
        @queue      = attributes[:queue]
        @attempts   = attributes[:attempts]
        @failed_at  = attributes[:failed_at]
        @locked_at  = attributes[:locked_at]
        @locked_by  = attributes[:locked_by]
        @last_error = attributes[:last_error]
        @handler    = attributes[:handler]
      end

      def to_param
        id
      end

      def queue!
        true
      end

      def destroy
        self
      end

      def self.find *args
        decorate build_failed
      end

      def self.all
        [build_executing, build_failed, build_queued].map do |job|
          decorate job
        end
      end

      def self.decorate job
        StatusDecorator.new job
      end

      def self.build_executing
        new id: 1, created_at: 1.minute.ago, run_at: 1.minute.ago,
          attempts: 1, last_error: nil, locked_at: 30.seconds.ago,
          locked_by: 'host.local', handler: '---'
      end

      def self.build_failed
        new id: 2, created_at: 5.hours.ago, run_at: 2.hours.from_now,
          attempts: 4, failed_at: 1.hour.ago, last_error: 'RuntimeError: RuntimeError',
          locked_at: nil, locked_by: nil, handler: '---'
      end

      def self.build_queued
        new id: 3, created_at: 30.seconds.ago, run_at: 30.seconds.ago,
          attempts: 0, last_error: nil, locked_at: nil, locked_by: nil,
          handler: '---'
      end
    end
  end
end

app/models/delayed/web/job/mongoid.rb
module Delayed
  module Web
    class Job::Mongoid

      def self.find *args
        decorate Delayed::Job.find(*args)
      end

      def self.all
        jobs = Delayed::Job.order_by(created_at: 'desc').limit(100)
        Enumerator.new do |enumerator|
          jobs.each do |job|
            enumerator.yield decorate(job)
          end
        end
      end

      def self.decorate job
        ActiveRecordDecorator.new StatusDecorator.new(job)
      end

    end
  end
end

app/controllers/delayed/dashboard/jobs_controller.rb
module Delayed
  module Dashboard
    class JobsController < ApplicationController
    private

      def job
        @job ||= Delayed::Dashboard::Job.find params[:id]
      end
      helper_method :job

      def jobs
        @jobs ||= Delayed::Dashboard::Job.all
      end
      helper_method :jobs
    end
  end
end

app/controllers/delayed/web/jobs_controller.rb
module Delayed
  module Web
    class JobsController < Delayed::Web::ApplicationController
      def queue
        if job.can_queue?
          job.queue!
          flash[:notice] = t(:notice, scope: 'delayed/web.flashes.jobs.queued')
        else
          status = t(job.status, scope: 'delayed/web.views.statuses')
          flash[:alert] = t(:alert, scope: 'delayed/web.flashes.jobs.queued', status: status)
        end
        redirect_to jobs_path
      end

      def destroy
        if job.can_destroy?
          job.destroy
          flash[:notice] = t(:notice, scope: 'delayed/web.flashes.jobs.destroyed')
        else
          status = t(job.status, scope: 'delayed/web.views.statuses')
          flash[:alert] = t(:alert, scope: 'delayed/web.flashes.jobs.destroyed', status: status)
        end
        redirect_to jobs_path
      end

      private

      def job
        begin
          @job ||= Delayed::Web::Job.find(params[:id])
        rescue ActiveRecord::NotFound
          flash[:notice] = t(:notice, scope: 'delayed/web.flashes.jobs.executed')
          redirect_to jobs_path and return
        end
      end
      helper_method :job

      def jobs
        @jobs ||= Delayed::Web::Job.all
      end
      helper_method :jobs
    end
  end
end

app/helpers/delayed/dashboard/jobs_helper.rb
module Delayed::Dashboard::JobsHelper
  def status_text job
    case
    when job.locked_at && job.locked_by
      'executing'
    when job.attempts > 0 && job.last_error.present?
      'failed'
    else
      'queued'
    end
  end

  def status_dom_class job
    case status_text job
    when 'executing' then 'badge badge-warning'
    when 'failed'    then 'badge badge-important'
    else                  'badge'
    end
  end
end

app/helpers/delayed/web/jobs_helper.rb
module Delayed::Web::JobsHelper
  def status_dom_class status
    case status
    when 'executing' then 'badge badge-warning'
    when 'failed'    then 'badge badge-important'
    else                  'badge'
    end
  end
end

app/views/delayed/web/jobs/index.html.erb
<% title t('delayed/web.views.jobs') %>

<div class="page-header">
  <h1><%= title %></h1>
  <h3><%= t('delayed/web.views.server_time') %> <%= l(Time.now, format: :short)%><h3>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= t('delayed/web.views.id') %></th>
      <th><%= t('delayed/web.views.status') %></th>
      <th><%= t('delayed/web.views.current_queue') %></th>
      <th><%= t('delayed/web.views.created_at') %></th>
      <th><%= t('delayed/web.views.run_at') %></th>
      <th><%= t('delayed/web.views.attempts') %></th>
      <th style="width: 190px;"><%= t('delayed/web.views.last_error') %></th>
      <th style="width: 140px"><%= t('delayed/web.views.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% if jobs.any? %>
      <% jobs.each do |job| %>
        <tr>
          <td><%= link_to "##{job.id}", job_path(job) %></td>
          <td>
            <span class="<%= status_dom_class(job.status) %>">
              <%= t(job.status, scope: 'delayed/web.views.statuses').capitalize %>
            </span>
          </td>
          <td><%= job.queue %></td>
          <td style="font-size: 12px;"><%= l(job.created_at, format: :short) %></td>
          <td style="font-size: 12px;"><%= l(job.run_at, format: :short) %></td>
          <td><%= job.attempts %></td>
          <td>
            <% if job.last_error.present? %>
              <%= link_to truncate(job.last_error), job_path(job) %>
            <% else %>
              <span class="label label-success"><%= t('delayed/web.views.errors.empty') %></span>
            <% end %>
          </td>
          <td>
            <% if job.can_queue? %>
              <%= button_to t('delayed/web.views.buttons.run_next'), queue_job_path(job), method: :put, class: 'btn btn-mini btn-action', form_class: 'btn-rails pull-left', title: t('delayed/web.views.buttons.run_next') %>
            <% end %>
            <% if job.can_destroy? %>
              <%= button_to t('delayed/web.views.buttons.delete'), job_path(job), method: :delete, class: 'btn btn-danger btn-mini btn-action', form_class: 'btn-rails pull-right', title: t('delayed/web.views.buttons.delete'), onclick: "return confirm('#{t('delayed/web.views.confirm.delete')}')" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="7">
          <%= t('delayed/web.views.queue.empty') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/delayed/web/jobs/show.html.erb
<% title "#{t('delayed/web.views.job')} ##{job.id}" %>

<div class="page-header">
  <h1>
    <%= link_to t('delayed/web.views.jobs'), jobs_path %> / <%= title %>
  </h1>
  <div class="btn-group">
    <% if job.can_queue? %>
      <%= button_to t('delayed/web.views.buttons.run_next'), queue_job_path(job), method: :put, class: 'btn', form_class: 'btn-rails pull-left' %>
    <% end %>
    <% if job.can_destroy? %>
      <%= button_to t('delayed/web.views.buttons.delete'), job_path(job), method: :delete, class: 'btn btn-danger', form_class: 'btn-rails pull-right', onclick: "return confirm('#{t('delayed/web.views.confirm.delete')}')" %>
    <% end %>
  </div>
</div>

<h2><%= t('delayed/web.views.status') %></h2>
<p class="<%= status_dom_class(job.status) %>">
  <%= t(job.status, scope: 'delayed/web.views.statuses').capitalize %>
</p>

<h2><%= t('delayed/web.views.queue.title') %></h2>
<p class="<%= status_dom_class(job.status) %>">
  <%= job.queue.capitalize %>
</p>

<h2><%= t('delayed/web.views.last_error') %></h2>
<% if job.last_error.present? %>
  <pre><%= job.last_error %></pre>
<% else %>
  <p class="label label-success"><%= t('delayed/web.views.errors.empty') %></p>
<% end %>

<h2><%= t('delayed/web.views.handler') %></h2>
<pre><%= job.handler %></pre>